language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "yarn global add gatsby-cli"
  - "yarn"
script:
  - "yarn run build"
after_success:
  - "yarn run deploy"
