language: node_js
node_js:
  - "10.18.1"
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm install -g gatsby-cli"
  - "npm i"
script:
  - "npm run build"
after_success:
  - "npm run deploy"
