language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i --global gatsby-cli"
  - "npm i"
script:
  - "npm run build"
after_success:
  - "npm run deploy"
